@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 20
skinparam ranksep 30
skinparam packageStyle rectangle
skinparam packageBorderColor #444
skinparam packageBackgroundColor #F9F9F9
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #444
skinparam classFontStyle bold
skinparam arrowColor #444
skinparam arrowThickness 1.5

package "Aggregate Language" {
  class Language <<AggregateRoot>> {
  }
}

package "Aggregate Drone Model" {
  class DroneModel <<AggregateRoot>> {
    ModelSpecifications: List<String>
  }
}

package "Aggregate Client" {
  class Client <<AggregateRoot>> {
   }

  class Representative <<Entity>>{
  }

  class VAT <<(V, #aadddd) ValueObject>>{
    Value: String
  }

  class Address <<(V, #aadddd) ValueObject>>{
    Value: String
  }
}

package "Aggregate Show Request" {
  class ShowRequest <<AggregateRoot>> {
    DronesNum: int
    Duration: int
    ShowDescription: String
  }
}

package "Aggregate Drone" {
  class Drone <<AggregateRoot>> {

  }

  class Maintenance <<Entity>> {
    Description: String
  }

  class SerialNumber <<(V, #aadddd) ValueObject>> {
    Value: String
  }
}

package "Aggregate Show Proposal" {
  class ShowProposal <<AggregateRoot>> {
    ProposalDronesNum: int
    ProposalDuration: int
    ProposalDescription: String
  }

  class Status <<(V, #aadddd) ValueObject>> {
    Value: String
  }

  class Report <<(V, #aadddd) ValueObject>> {
    Value: String
  }
}

package "Aggregate User" {
  class User <<AggregateRoot>> {
  }

  class Username <<(V, #aadddd) ValueObject>> {
    Value: String
  }

  class Password <<(V, #aadddd) ValueObject>> {
    Value: String
  }

  class Email <<(V, #aadddd) ValueObject>> {
    Value: String
  }

  class Phone <<(V, #aadddd) ValueObject>> {
    Value: String
  }
}

package "Aggregate Figure" {
  class Figure <<AggregateRoot>> {
    Description: String
    Exclusive: Boolean
  }
}

class Name <<(V, #aadddd) ValueObject>>{
  Value: String
}

class Id <<(V, #aadddd) ValueObject>> {
  Value: String
}

class DateValue <<(V, #aadddd) ValueObject>> {
  Value: String
}

' --- Associations ---

Language --> Name : LanguageName
DroneModel --> Language: Language
DroneModel --> Id: ClientName
Drone --> DroneModel: Model
Drone --> SerialNumber: DroneSerialNumber
Drone --> Maintenance: MaintenanceHistory: List<Maintenance>
Drone --> Id: DroneId

Maintenance --> Id: MaintenanceId
Maintenance --> DateValue: MaintenanceStartDate
Maintenance --> DateValue: MaintenanceEndDate

ShowProposal --> Client: Client
ShowProposal --> Drone: DronesPropostal: List<Drone>
ShowProposal --> Status: ProposalStatus
ShowProposal --> Report: SimulationResult
ShowProposal --> Figure: Figures: List<Figure>
ShowProposal --> Id: ProposalId
ShowProposal --> DateValue: ProposalDate

Figure --> Client: Client
Figure --> Id: FigureId

User --> Id: UserId
User --> Username: Username
User --> Password: UserPassword
User --> Email: UserEmail
User --> Phone: UserPhone

ShowRequest --> Client: Customer
ShowRequest --> Id: ShowRequestId
ShowRequest --> DateValue: ShowRequestDate
ShowRequest --> Address: Place

Client --> Representative: Representatives: List<Representative>
Client --> VAT: ClientVAT
Client --> Address: ClientAddress
Client --> Id: ClientId
Client --> Name: ClientName

Representative --> Id: RepresentativeId
Representative --> Name: RepresentativeName


@enduml

