@startuml

hide methods



package "Aggregate Client " {

    ' Agregado Client (Aggregate Root)
    class Client <<AggregateRoot>> {
        ClientID: Id
        ClientName: Name
        ClientVAT: VAT
        ClientAddress: Address
        Representatives: List<Representative>
    }

    class VAT <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Address <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Representante (Gestor do sistema é um tipo de User, aqui é o representante do cliente)
    class Representative <<Entity>> {
        RepresentativeId: Id
        RepresentativeName: Name
    }

    Client --> VAT
    Client --> Representative
    Client --> Address
}
    Client --> Id
    Representative --> Id
        Representative --> Name
    Client --> Name

package "Aggregate Drone" {

    ' Agregado Drone (Aggregate Root)
    class Drone <<AggregateRoot>> {
        DroneId: Id
        DroneSerialNumber: SerialNumber
        MaintenanceHistory: List<Maintenance>
        DroneModelId: Id
    }

    ' Entidade Maintenance associada ao drone
    class Maintenance <<Entity>> {
        MaintenanceId: Id
        MaintenanceStartDate: DateValue
        MaintenanceEndDate: DateValue
        Description: String
    }

    class SerialNumber <<(V, #007fff) ValueObject>> {
        value: String
    }


    Drone --> SerialNumber
    Drone --> Maintenance

}

    Drone --> Id
    Maintenance --> Id
        Maintenance --> DateValue

package "Aggregate Show Proposal" {

    ' Agregado ShowProposal (Aggregate Root)
    class ShowProposal <<AggregateRoot>> {
        ProposalId: Id
        Client: Client
        ProposalDate: DateValue
        ProposalStatus: Status
        Figures: List<FigureId>
        SimulationResult: Report
    }



    class Status <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Report <<(V, #007fff) ValueObject>> {
        value: String
    }

    ShowProposal --> Status
    ShowProposal --> Report
}
    ShowProposal --> Id
        ShowProposal --> DateValue

package "Aggregate Show Request " {

    ' Agregado ShowRequest (Aggregate Root)
    class ShowRequest <<AggregateRoot>> {
        ShowRequestId: Id
        Client: Client
        Description: String
    }


}
    ShowRequest --> Id

package "Aggregate User" {

    ' Agregado User (Aggregate Root)
    class User <<AggregateRoot>> {
        UserId: Id
        Username: Username
        Password: Password
        Email: String
        Phone: String
    }

    class Username <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Password <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    User --> Username
    User --> Password
}
    User --> Id

package "Aggregate Language " {

    class Language <<AggregateRoot>> {
        LanguageName: Name
    }

}
    Language --> Name

package "Aggregate Figure " {

    ' Agregado Figure (Aggregate Root)
    class Figure <<AggregateRoot>> {
        FigureId: Id
        ClientId: Id
        Description: String
        Exclusive: Boolean
    }


}
    Figure --> Id

package " Aggregate Drone Model " {

    ' Agregado DroneModel (Aggregate Root)
    class DroneModel <<AggregateRoot>> {
        DroneModelId: Id
        Language: Language
        ModelSpecifications: Specifications
    }

    class Specifications <<Entity>> {
        dimensions: String
        weight: String
        maxSpeed: String
        flightTime: String
    }

    ' Ligações
    DroneModel --> Specifications
}
    DroneModel --> Id


DroneModel --> Language
Client <-- ShowRequest



class Id <<(V, #007fff) ValueObject>> {
    value: String
}

    class Name <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DateValue <<(V, #007fff) ValueObject>> {
        value: String
    }

ShowProposal --> Client

Figure <-- ShowProposal

@enduml