@startuml
hide methods

package "Aggregate Drone" {

    ' Agregado Drone (Aggregate Root)
    class Drone <<AggregateRoot>> {
        id: DroneId
        serialNumber: String
        state: DroneState
        maintenanceHistory: List<Maintenance>
        droneModelId: DroneModelId
    }

    ' Entidade Maintenance associada ao drone
    class Maintenance <<Entity>> {
        id: MaintenanceId
        maintenanceStartDate: DateValue
        maintenanceEndDate: DateValue
        description: String
    }

    class MaintenanceId <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Value Objects
    class DroneId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DroneState <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DroneModelId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DateValue <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    Drone --> DroneId
    Drone --> DroneState
    Drone --> DroneModelId
    Drone "1" -- "*" Maintenance : has
    Maintenance --> MaintenanceId
    Maintenance --> DateValue
}
@enduml
