@startuml
hide methods

package "Aggregate Show Request " {

    ' Agregado ShowRequest (Aggregate Root)
    class ShowRequest <<AggregateRoot>> {
        ShowRequestId: Id
        ClientId: Id
        Description: String
    }

    ' Value Objects associados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    ShowRequest --> Id
}
@enduml