@startuml
hide methods

package "Aggregate User" {

    ' Agregado User (Aggregate Root)
    class User <<AggregateRoot>> {
        id: UserId
        username: Username
        password: Password
        email: String
        phone: String
    }

    ' Value Objects associados
    class UserId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Username <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Password <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    User --> UserId
    User --> Username
    User --> Password
}
@enduml