@startuml
hide methods

package " Aggregate Drone Model " {

    ' Agregado DroneModel (Aggregate Root)
    class DroneModel <<AggregateRoot>> {
        DroneModelId: Id
        Language: Language
        ModelSpecifications: Specifications
    }

    ' Value Objects associados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Specifications <<Entity>> {
        dimensions: String
        weight: String
        maxSpeed: String
        flightTime: String
    }

    ' Ligações
    DroneModel --> Id
    DroneModel --> Specifications
}
@enduml
