@startuml
hide methods

package "Aggregate Show Request " {

    ' Agregado ShowRequest (Aggregate Root)
    class ShowRequest <<AggregateRoot>> {
        id: ShowRequestId
        description: Description
    }

    ' Value Objects associados
    class ShowRequestId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Description <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    ShowRequest --> ShowRequestId
    ShowRequest --> Description
}
@enduml