@startuml
hide methods

package "Aggregate Figure " {

    ' Agregado Figure (Aggregate Root)
    class Figure <<AggregateRoot>> {
        FigureId: Id
        ClientId: Id
        Description: String
        Exclusive: Boolean
    }

    ' Value Objects relacionados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    Figure --> Id
}

package " Aggregate Drone Model " {

    ' Agregado DroneModel (Aggregate Root)
    class DroneModel <<AggregateRoot>> {
        DroneModelId: Id
        Name: String
        language: String
        manufacturer: String
        specifications: ModelSpecifications
    }

    ' Value Objects associados
    class DroneModelId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class ModelSpecifications <<(V, #007fff) ValueObject>> {
        dimensions: String
        weight: String
        maxSpeed: String
        flightTime: String
    }

    ' Ligações
    DroneModel --> DroneModelId
    DroneModel --> ModelSpecifications
}
@enduml
