@startuml
package "Aggregate Show " {

    ' Agregado Show (Aggregate Root)
    class Show <<AggregateRoot>> {
        - id: ShowId
        - date: DateValue
        - figureIds: List<FigureId>
        - droneIds: List<DroneId>
    }

    ' Value Objects relacionados
    class ShowId <<ValueObject>> {
        - value: String
    }

    class DateValue <<ValueObject>> {
        - value: String
    }

    class FigureId <<ValueObject>> {
        - value: String
    }

    class DroneId <<ValueObject>> {
        - value: String
    }

    ' Ligações
    Show --> ShowId
    Show --> DateValue
    Show --> FigureId
    Show --> DroneId
}
@enduml
