@startuml
hide methods

package "Aggregate Show " {

    ' Agregado Show (Aggregate Root)
    class Show <<AggregateRoot>> {
        ShowId: Id
        Date: DateValue
        Figures: List<FigureId>
        Drones: List<DroneId>
    }

    ' Value Objects relacionados
    class ShowId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DateValue <<(V, #007fff) ValueObject>> {
        value: String
    }

    class FigureId <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DroneId <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    Show --> ShowId
    Show --> DateValue
    Show --> FigureId
    Show --> DroneId
}
@enduml
