@startuml
hide methods

package "Aggregate Drone" {

    ' Agregado Drone (Aggregate Root)
    class Drone <<AggregateRoot>> {
        DroneId: Id
        DroneSerialNumber: SerialNumber
        MaintenanceHistory: List<Maintenance>
        DroneModelId: Id
    }

    ' Entidade Maintenance associada ao drone
    class Maintenance <<Entity>> {
        MaintenanceId: Id
        MaintenanceStartDate: DateValue
        MaintenanceEndDate: DateValue
        Description: String
    }

    ' Value Objects
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    class SerialNumber <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DateValue <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    Drone --> Id
    Drone --> SerialNumber
    Drone --> Maintenance
    Maintenance --> Id
    Maintenance --> DateValue

}
@enduml
