@startuml
hide methods

package "Aggregate Figure " {

    ' Agregado Figure (Aggregate Root)
    class Figure <<AggregateRoot>> {
        FigureId: Id
        ClientId: Id
        Description: String
        Exclusive: Boolean
    }

    ' Value Objects relacionados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    Figure --> Id
}

@enduml
