@startuml
hide methods

package "Aggregate Show Proposal" {

    ' Agregado ShowProposal (Aggregate Root)
    class ShowProposal <<AggregateRoot>> {
        ProposalId: Id
        ClientId: Id
        ProposalDate: DateValue
        ProposalStatus: Status
        Figures: List<FigureId>
        SimulationResult: Report
    }

    ' Value Objects associados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    class DateValue <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Status <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Report <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    ShowProposal --> Id
    ShowProposal --> DateValue
    ShowProposal --> Status
    ShowProposal --> Report
}
@enduml
