@startuml
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam shadowing false

' US322 - Class Diagram for Listing Types
class ListMaintenanceTypesController {
  + listAllTypes() : Iterable<MaintenanceType>
}
class MaintenanceTypeRepository {
  + findAll() : List<MaintenanceType>
}
ListMaintenanceTypesController --> MaintenanceTypeRepository
@enduml
