@startuml
hide methods

package "Aggregate User" {

    ' Agregado User (Aggregate Root)
    class User <<AggregateRoot>> {
        UserId: Id
        Username: Username
        Password: Password
        Email: String
        Phone: String
    }

    ' Value Objects associados
    class Id <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Username <<(V, #007fff) ValueObject>> {
        value: String
    }

    class Password <<(V, #007fff) ValueObject>> {
        value: String
    }

    ' Ligações
    User --> Id
    User --> Username
    User --> Password
}
@enduml